spring.application.name=SimpleWebApp

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/Alien
spring.datasource.username=root
spring.datasource.password=Aryan2005@
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
